Update dependency for latest K8s
cybozu-go/moco-agent pull request #93
Opened 2024-05-17 00:25 UTC by takara9

2024-05-20 02:39 UTC, masa213f requested changes
This repository does not depend on k8s. Please fix the title of the PR.

2024-05-20 02:39 UTC, masa213f commented on Makefile
> -MYSQL_VERSION = 8.0.28
I'm not sure. Does this pass the test?

https://github.com/cybozu-go/moco-agent/issues/77

2024-06-07 00:58 UTC, takara9 commented on Makefile
> -MYSQL_VERSION = 8.0.28
updated MYSQL_VERSION = 8.0.37

2024-06-07 08:33 UTC, masa213f approved these changes

2024-06-10 07:55 UTC, merged

2024-06-11 05:34 UTC, shunki-fujita commented on Makefile
> -MYSQL_VERSION = 8.0.28
@takara9 @masa213f 
ここも更新しないとCI動かなくないですか？
https://github.com/cybozu-go/moco-agent/blob/09b017017458054f36c89e0eb62672c3d3c8184d/.github/workflows/ci.yaml#L46

2024-06-12 09:39 UTC, masa213f commented on Makefile
> -MYSQL_VERSION = 8.0.28
@shunki-fujita 
Thanks. I update it in https://github.com/cybozu-go/moco-agent/pull/95.